version: '3.8'

services:
  backend_app: # Updated service name
    build:
      context: ./backend 
      dockerfile: Dockerfile
    image: backend:v1 # Added image name and tag
    ports:
      - "5001:5001" 
    volumes:
      - ./backend/users.json:/app/users.json 
      # - ./backend:/app # For development live reload
    networks:
      - login_app_network 
    restart: unless-stopped

  frontend_app: # Updated service name
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    image: frontend:v1 # Added image name and tag
    ports:
      - "5000:5000" 
    volumes:
      - ./frontend/templates:/app/templates 
      # - ./frontend:/app # For development live reload
    depends_on:
      - backend_app # Updated dependency
    environment:
      - BACKEND_API_URL=http://backend_app:5001/api # Updated backend service name in URL
      - FLASK_DEBUG=1 
    networks:
      - login_app_network 
    restart: unless-stopped

networks:
  login_app_network: 
    driver: bridge