#version: '3.8'

services:
  backend-app: # This is the service name, used for inter-service communication
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:v1.1 # This is the image name and tag
    container_name: backend-app # Explicit container name
    ports:
      - "5001:5001"
    volumes:
      - ./backend/users.json:/app/users.json
      # - ./backend:/app # For development live reload
    networks:
      - login-app-network
    restart: unless-stopped

  frontend-app: # This is the service name
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:v1.1 # This is the image name and tag
    container_name: frontend-app # Explicit container name
    ports:
      - "5000:5000"
    depends_on:
      - backend-app # Depends on the service name
    environment:
      # This URL uses the backend service name (backend_app), which Docker Compose resolves
      - BACKEND_API_URL=http://backend-app:5001/api
    networks:
      - login-app-network
    restart: unless-stopped

networks:
  login-app-network:
    driver: bridge