#version: '3.8'

services:
  backend_app: # This is the service name, used for inter-service communication
    build:
      context: ./backend 
      dockerfile: Dockerfile
    image: backend:v1 # This is the image name and tag
    container_name: backend_app_container # Explicit container name
    ports:
      - "5001:5001" 
    volumes:
      - ./backend/users.json:/app/users.json 
      # - ./backend:/app # For development live reload
    networks:
      - login_app_network 
    restart: unless-stopped

  frontend_app: # This is the service name
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    image: frontend:v1 # This is the image name and tag
    container_name: frontend_app_container # Explicit container name
    ports:
      - "5000:5000" 
    volumes:
      - ./frontend/templates:/app/templates 
      # - ./frontend:/app # For development live reload
    depends_on:
      - backend_app # Depends on the service name
    environment:
      # This URL uses the backend service name (backend_app), which Docker Compose resolves
      - BACKEND_API_URL=http://backend_app:5001/api 
      - FLASK_DEBUG=1 
    networks:
      - login_app_network 
    restart: unless-stopped

networks:
  login_app_network: 
    driver: bridge
